name: Clone external repo

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKENTEST }}

      - name: Clone external repo
        run: |
          git clone https://github.com/papasgamesfree/papasgamesfree.github.io.git external-repo

      - name: Copy contents to current repo
        run: |
          cp -r external-repo/* .
          rm -rf external-repo

      - name: Commit and push
        run: |
          git config --global user.name "ktmanh"
          git config --global user.email "kieutrimanh@gmail.com"
          git add .
          git commit -m "Cloned and copied external repo"
          git push
